-- SIGAA Hub UFBA — Fase 2: consistência, antiabuso e autorização.
-- Esta migration evolui as estruturas reais: public.links e public.link_reports.

begin;

-- -----------------------------------------------------------------------------
-- Links: saneamento determinístico e unicidade concorrente
-- -----------------------------------------------------------------------------

alter table public.links
  add column if not exists inactive_reason text;

comment on column public.links.inactive_reason is
  'Motivo técnico controlado para desativação. Não armazenar texto livre do usuário.';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'links_inactive_reason_check'
      and conrelid = 'public.links'::regclass
  ) then
    alter table public.links
      add constraint links_inactive_reason_check
      check (
        inactive_reason is null
        or inactive_reason in (
          'reports_threshold',
          'deduplicated_active_link',
          'manual_review'
        )
      ) not valid;
  end if;
end;
$$;

-- Mantém o link ativo mais recente de cada turma. Empates são resolvidos por id.
-- Nenhum registro é excluído; os excedentes são desativados e identificados.
with ranked_active_links as (
  select
    id,
    row_number() over (
      partition by turma_id
      order by created_at desc, id desc
    ) as active_rank
  from public.links
  where is_active is true
)
update public.links as links
set
  is_active = false,
  inactive_reason = coalesce(links.inactive_reason, 'deduplicated_active_link')
from ranked_active_links
where links.id = ranked_active_links.id
  and ranked_active_links.active_rank > 1;

create unique index if not exists one_active_link_per_class
  on public.links (turma_id)
  where is_active is true;

alter table public.links validate constraint links_inactive_reason_check;

-- -----------------------------------------------------------------------------
-- Denúncias existentes
-- -----------------------------------------------------------------------------

create table if not exists public.link_reports (
  id uuid primary key default gen_random_uuid(),
  link_id uuid not null references public.links(id) on delete cascade,
  motivo text not null,
  reporter_fingerprint text,
  country_code text,
  created_at timestamptz not null default now(),
  constraint link_reports_motivo_length
    check (char_length(btrim(motivo)) between 10 and 150),
  constraint link_reports_fingerprint_format
    check (
      reporter_fingerprint is null
      or reporter_fingerprint ~ '^[0-9a-f]{64}$'
    ),
  constraint link_reports_country_code_format
    check (country_code is null or country_code ~ '^[A-Z]{2}$')
);

create index if not exists link_reports_link_id_created_at_idx
  on public.link_reports (link_id, created_at desc);

create index if not exists link_reports_fingerprint_created_at_idx
  on public.link_reports (reporter_fingerprint, created_at desc)
  where reporter_fingerprint is not null;

-- A implementação anterior bloqueava a origem para sempre. A Fase 2 usa uma
-- janela explícita de 24 horas e serialização por advisory lock.
drop index if exists public.link_reports_unique_reporter_per_link_idx;

alter table public.link_reports enable row level security;
revoke all on table public.link_reports from public, anon, authenticated;
grant select, insert, update, delete on table public.link_reports to service_role;

-- -----------------------------------------------------------------------------
-- Eventos persistentes de rate limiting
-- -----------------------------------------------------------------------------

create table if not exists public.abuse_events (
  id bigint generated by default as identity primary key,
  action_scope text not null,
  reporter_fingerprint text not null,
  resource_id uuid,
  outcome text not null,
  created_at timestamptz not null default now(),
  constraint abuse_events_action_scope_check
    check (
      action_scope in (
        'add_link_attempt',
        'add_link_success',
        'report_link_attempt',
        'report_link_success'
      )
    ),
  constraint abuse_events_fingerprint_format
    check (reporter_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint abuse_events_outcome_check
    check (
      outcome in (
        'attempted',
        'accepted',
        'rate_limited',
        'duplicate',
        'inactive',
        'not_found',
        'active_link_exists'
      )
    )
);

comment on table public.abuse_events is
  'Eventos pseudonimizados para rate limiting. Retenção operacional de 30 dias.';
comment on column public.abuse_events.reporter_fingerprint is
  'HMAC SHA-256 calculado no servidor. Nunca contém o IP bruto.';
comment on column public.abuse_events.resource_id is
  'Identificador técnico opcional do recurso; não contém URL nem conteúdo do formulário.';

create index if not exists abuse_events_scope_fingerprint_created_at_idx
  on public.abuse_events (action_scope, reporter_fingerprint, created_at desc);

create index if not exists abuse_events_resource_fingerprint_created_at_idx
  on public.abuse_events (resource_id, reporter_fingerprint, created_at desc)
  where resource_id is not null;

create index if not exists abuse_events_created_at_idx
  on public.abuse_events (created_at);

alter table public.abuse_events enable row level security;
revoke all on table public.abuse_events from public, anon, authenticated;
grant select, insert, update, delete on table public.abuse_events to service_role;
grant usage, select on sequence public.abuse_events_id_seq to service_role;

-- -----------------------------------------------------------------------------
-- Limpeza limitada e controlada
-- -----------------------------------------------------------------------------

create or replace function public.cleanup_expired_abuse_events(
  p_retention interval default interval '30 days',
  p_batch_size integer default 500
)
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_deleted integer := 0;
  v_retention interval;
  v_batch_size integer;
begin
  v_retention := coalesce(p_retention, interval '30 days');
  v_batch_size := greatest(1, least(coalesce(p_batch_size, 500), 5000));

  if v_retention < interval '1 day' then
    raise exception 'Retention interval is below the allowed minimum.'
      using errcode = '22023';
  end if;

  with expired as (
    select id
    from public.abuse_events
    where created_at < now() - v_retention
    order by created_at
    limit v_batch_size
  )
  delete from public.abuse_events as events
  using expired
  where events.id = expired.id;

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$function$;

comment on function public.cleanup_expired_abuse_events(interval, integer) is
  'Remove em lote eventos antiabuso expirados. Uso interno/service_role.';

revoke all on function public.cleanup_expired_abuse_events(interval, integer)
  from public, anon, authenticated;
grant execute on function public.cleanup_expired_abuse_events(interval, integer)
  to service_role;

-- -----------------------------------------------------------------------------
-- Cadastro transacional de link
-- Limites: 5 tentativas/hora e 2 sucessos/24h por fingerprint de add_link.
-- -----------------------------------------------------------------------------

create or replace function public.add_link_secure(
  p_turma_id uuid,
  p_url_whatsapp text,
  p_reporter_fingerprint text
)
returns text
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_url text;
  v_fingerprint text;
  v_attempts_last_hour integer;
  v_successes_last_day integer;
begin
  if p_turma_id is null then
    return 'not_found';
  end if;

  v_url := btrim(coalesce(p_url_whatsapp, ''));
  if v_url !~ '^https://chat\.whatsapp\.com/[A-Za-z0-9_-]+/?$' then
    raise exception 'Invalid WhatsApp invite URL.' using errcode = '22023';
  end if;

  v_fingerprint := lower(btrim(coalesce(p_reporter_fingerprint, '')));
  if v_fingerprint !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid reporter fingerprint.' using errcode = '22023';
  end if;

  -- Serializa contagem e escrita para a mesma origem sem armazenar o IP.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('add_link:' || v_fingerprint, 0)
  );

  insert into public.abuse_events (
    action_scope,
    reporter_fingerprint,
    resource_id,
    outcome
  ) values (
    'add_link_attempt',
    v_fingerprint,
    p_turma_id,
    'attempted'
  );

  select count(*)::integer
  into v_attempts_last_hour
  from public.abuse_events
  where action_scope = 'add_link_attempt'
    and reporter_fingerprint = v_fingerprint
    and created_at >= now() - interval '1 hour';

  if v_attempts_last_hour > 5 then
    update public.abuse_events
    set outcome = 'rate_limited'
    where id = (
      select id
      from public.abuse_events
      where action_scope = 'add_link_attempt'
        and reporter_fingerprint = v_fingerprint
      order by id desc
      limit 1
    );
    return 'rate_limited';
  end if;

  select count(*)::integer
  into v_successes_last_day
  from public.abuse_events
  where action_scope = 'add_link_success'
    and reporter_fingerprint = v_fingerprint
    and created_at >= now() - interval '24 hours';

  if v_successes_last_day >= 2 then
    update public.abuse_events
    set outcome = 'rate_limited'
    where id = (
      select id
      from public.abuse_events
      where action_scope = 'add_link_attempt'
        and reporter_fingerprint = v_fingerprint
      order by id desc
      limit 1
    );
    return 'rate_limited';
  end if;

  if not exists (select 1 from public.turmas where id = p_turma_id) then
    update public.abuse_events
    set outcome = 'not_found'
    where id = (
      select id
      from public.abuse_events
      where action_scope = 'add_link_attempt'
        and reporter_fingerprint = v_fingerprint
      order by id desc
      limit 1
    );
    return 'not_found';
  end if;

  begin
    insert into public.links (turma_id, url_whatsapp, reports, is_active)
    values (p_turma_id, v_url, 0, true);
  exception
    when unique_violation then
      update public.abuse_events
      set outcome = 'active_link_exists'
      where id = (
        select id
        from public.abuse_events
        where action_scope = 'add_link_attempt'
          and reporter_fingerprint = v_fingerprint
        order by id desc
        limit 1
      );
      return 'active_link_exists';
  end;

  insert into public.abuse_events (
    action_scope,
    reporter_fingerprint,
    resource_id,
    outcome
  ) values (
    'add_link_success',
    v_fingerprint,
    p_turma_id,
    'accepted'
  );

  -- Limpeza oportunista e limitada; não varre toda a tabela por requisição.
  if pg_catalog.random() < 0.02 then
    perform public.cleanup_expired_abuse_events(interval '30 days', 250);
  end if;

  return 'added';
end;
$function$;

comment on function public.add_link_secure(uuid, text, text) is
  'Valida rate limit e cria um link ativo atomicamente, protegido por índice único parcial.';

-- -----------------------------------------------------------------------------
-- Denúncia transacional
-- Limites: 10 tentativas/hora e 1 denúncia/link/24h por fingerprint de report.
-- -----------------------------------------------------------------------------

create or replace function public.report_link_secure(
  p_link_id uuid,
  p_motivo text,
  p_reporter_fingerprint text
)
returns text
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_motivo text;
  v_fingerprint text;
  v_attempts_last_hour integer;
  v_link public.links%rowtype;
  v_new_reports integer;
begin
  if p_link_id is null then
    return 'not_found';
  end if;

  v_motivo := btrim(coalesce(p_motivo, ''));
  if char_length(v_motivo) < 10 or char_length(v_motivo) > 150 then
    raise exception 'Invalid report reason.' using errcode = '22023';
  end if;

  v_fingerprint := lower(btrim(coalesce(p_reporter_fingerprint, '')));
  if v_fingerprint !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid reporter fingerprint.' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('report_link:' || v_fingerprint, 0)
  );

  insert into public.abuse_events (
    action_scope,
    reporter_fingerprint,
    resource_id,
    outcome
  ) values (
    'report_link_attempt',
    v_fingerprint,
    p_link_id,
    'attempted'
  );

  select count(*)::integer
  into v_attempts_last_hour
  from public.abuse_events
  where action_scope = 'report_link_attempt'
    and reporter_fingerprint = v_fingerprint
    and created_at >= now() - interval '1 hour';

  if v_attempts_last_hour > 10 then
    update public.abuse_events
    set outcome = 'rate_limited'
    where id = (
      select id
      from public.abuse_events
      where action_scope = 'report_link_attempt'
        and reporter_fingerprint = v_fingerprint
      order by id desc
      limit 1
    );
    return 'rate_limited';
  end if;

  if exists (
    select 1
    from public.link_reports
    where link_id = p_link_id
      and reporter_fingerprint = v_fingerprint
      and created_at >= now() - interval '24 hours'
  ) then
    update public.abuse_events
    set outcome = 'duplicate'
    where id = (
      select id
      from public.abuse_events
      where action_scope = 'report_link_attempt'
        and reporter_fingerprint = v_fingerprint
      order by id desc
      limit 1
    );
    return 'duplicate';
  end if;

  select *
  into v_link
  from public.links
  where id = p_link_id
  for update;

  if not found then
    update public.abuse_events
    set outcome = 'not_found'
    where id = (
      select id
      from public.abuse_events
      where action_scope = 'report_link_attempt'
        and reporter_fingerprint = v_fingerprint
      order by id desc
      limit 1
    );
    return 'not_found';
  end if;

  if v_link.is_active is not true then
    update public.abuse_events
    set outcome = 'inactive'
    where id = (
      select id
      from public.abuse_events
      where action_scope = 'report_link_attempt'
        and reporter_fingerprint = v_fingerprint
      order by id desc
      limit 1
    );
    return 'inactive';
  end if;

  insert into public.link_reports (
    link_id,
    motivo,
    reporter_fingerprint,
    country_code
  ) values (
    p_link_id,
    v_motivo,
    v_fingerprint,
    null
  );

  v_new_reports := coalesce(v_link.reports, 0) + 1;

  update public.links
  set
    reports = v_new_reports,
    is_active = v_new_reports < 3,
    inactive_reason = case
      when v_new_reports >= 3 then 'reports_threshold'
      else inactive_reason
    end
  where id = p_link_id;

  insert into public.abuse_events (
    action_scope,
    reporter_fingerprint,
    resource_id,
    outcome
  ) values (
    'report_link_success',
    v_fingerprint,
    p_link_id,
    'accepted'
  );

  if pg_catalog.random() < 0.02 then
    perform public.cleanup_expired_abuse_events(interval '30 days', 250);
  end if;

  if v_new_reports >= 3 then
    return 'deactivated';
  end if;

  return 'reported';
end;
$function$;

comment on function public.report_link_secure(uuid, text, text) is
  'Registra denúncia, incrementa o contador e desativa na terceira denúncia em uma única transação.';

-- A RPC anterior deixa de ser uma superfície pública após a migração.
drop function if exists public.incrementar_reports_link(uuid);
drop function if exists public.incrementar_reports_link(uuid, text, text, text);

-- -----------------------------------------------------------------------------
-- RLS e grants finais
-- -----------------------------------------------------------------------------

alter table public.disciplinas enable row level security;
alter table public.turmas enable row level security;
alter table public.links enable row level security;

revoke all on table public.disciplinas from public, anon, authenticated;
revoke all on table public.turmas from public, anon, authenticated;
revoke all on table public.links from public, anon, authenticated;

grant select on table public.disciplinas to anon, authenticated;
grant select on table public.turmas to anon, authenticated;
grant select on table public.links to anon, authenticated;

-- Remove a escrita direta; toda escrita pública passa pelas RPCs controladas.
revoke insert, update, delete on table public.links from anon, authenticated;

revoke all on function public.add_link_secure(uuid, text, text)
  from public, anon, authenticated;
revoke all on function public.report_link_secure(uuid, text, text)
  from public, anon, authenticated;

grant execute on function public.add_link_secure(uuid, text, text)
  to anon, authenticated, service_role;
grant execute on function public.report_link_secure(uuid, text, text)
  to anon, authenticated, service_role;

-- Preserva o acesso privilegiado necessário ao scraper e à operação do banco.
grant select, insert, update, delete on table public.disciplinas to service_role;
grant select, insert, update, delete on table public.turmas to service_role;
grant select, insert, update, delete on table public.links to service_role;

commit;
